name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  commit-msg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v6
        with:
          failOnWarnings: false

  build:
    needs: commit-msg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build (no test / no check)
        run: ./gradlew clean assemble
  lint:
    needs: commit-msg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint & Static Checks
        run: ./gradlew check -x test
  test:
    needs: commit-msg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: ./gradlew test